// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBidaOG9us4-l6ZDwJ8-pTwIKDo6O5BYyU',
    appId: '1:185449724504:web:011eb4267d16644cc6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    authDomain: 'ayurvan-b2bf2.firebaseapp.com',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
    measurementId: 'G-TXJXJ9N8KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxePqJRyMDJNzX0Y9Bl9DFBzRUMGHVZU',
    appId: '1:185449724504:android:5d0b9ec9f5c0b7a4c6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UOnrvRuNikww-vJ9MRkDbvIW_AbxgIo',
    appId: '1:185449724504:ios:d003c28d229ce4eec6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
    iosClientId: '185449724504-be4p2bje6u27p2vbgken4er0gmu7prh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayurvan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UOnrvRuNikww-vJ9MRkDbvIW_AbxgIo',
    appId: '1:185449724504:ios:d003c28d229ce4eec6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
    iosClientId: '185449724504-be4p2bje6u27p2vbgken4er0gmu7prh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayurvan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBidaOG9us4-l6ZDwJ8-pTwIKDo6O5BYyU',
    appId: '1:185449724504:web:20dca98a7f36d662c6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    authDomain: 'ayurvan-b2bf2.firebaseapp.com',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
    measurementId: 'G-6PWVL1YLNH',
  );
}
